# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  docker-tests:
    docker:
      - image: node
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Give Permission"
          command: chmod 0777 ./DiscoTicket/backend/node_modules/.bin/mocha
      - run:
          name: "Run Tests"
          command: cd DiscoTicket/backend ; docker run Dockerfile.test
  docker-server:
    docker:
      - image: circleci/node:10.8.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Start Server"
          command: cd DiscoTicket/backend ; node index.js

# Invoke jobs via workflows
workflows:
  docker-ci-tests:
    jobs:
      # - docker-server
      - docker-tests
