# # Use the latest 2.1 version of CircleCI pipeline process engine.
# version: 2.1

# # Define a job to be invoked later in a workflow.
# jobs:
#   docker-tests:
#     docker:
#       - image: modejota/vendorvert
#     resource_class: small
#     steps:
#       - checkout
#       - run:
#           name: "Running tests in Docker container"
#           command: npm run test

# # Invoke jobs via workflows
# workflows:
#   docker-ci-tests:
#     jobs:
#       - docker-tests

# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  docker-ci-tests: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          app-dir: "~/DiscoTicket/backend"
          version: "16.10"
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
