# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  # docker-tests:
  #   docker:
  #     - image: cimg/node:latest
  #   # resource_class: small
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Give Permission"
  #         command: chmod 0777 ./DiscoTicket/backend/node_modules/.bin/mocha
  #     - run:
  #         name: "Install node"
  #         command: cd DiscoTicket/backend ; npm i docker
  #     - run:
  #         name: "Run Tests"
  #         command: docker run Dockerfile.test
  docker-server:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: "Give Permission"
          command: chmod 0777 ./DiscoTicket/backend/node_modules/.bin/mocha
      - run:
          name: Install dependencies
          command: npm install ./DiscoTicket/backend/
      - run:
          name: install docker
          command: cd DiscoTicket/backend/ ; npm install -g docker
      - run:
          name: pull docker
          command: docker pull lauraroson99/laura_cc_22-23
      - run:
          name: testing
          command: docker run lauraroson99/laura_cc_22-23

# Invoke jobs via workflows
workflows:
  docker-ci-tests:
    jobs:
      - docker-server
      # - docker-tests
