# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  docker-tests:
    docker:
      - image: circleci/node:10.8.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: cd DiscoTicket/backend ; npm run test
  docker-server:
    docker:
      - image: circleci/node:10.8.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Start Server"
          command: cd DiscoTicket/backend ; node index.js
      # - run:
      #     name: "Running tests in Docker container"
      #     command: npm run test

# Invoke jobs via workflows
workflows:
  docker-ci-tests:
    jobs:
      # - docker-server
      - docker-tests
